# Generated by Django 5.2.5 on 2025-08-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trainerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('manager', 'Manager')], default='trainer', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='core.trainerprofile'),
        ),
    ]
